[package]
name = "rpg-class-simulator"
version = "0.1.0"
authors = ["Guillem Cordoba <guillem.cordoba@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roll-dice = "=0.1.0"